data_files: [
    '/content/videophy/examples/videocon_format_train1.csv',
    '/content/videophy/examples/videocon_format_val1.csv',
]

pretrained_ckpt: '/content/videophy/videocon/training/pipeline_video/mplug_owl_video'
